name: mealgrok
description: A tracking app for special diets.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqflite: ^1.1.8
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  charts_flutter: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/schema.sql
    - assets/config.yaml